if (MSVC)
    find_path(MAILIO_INCLUDE_DIR mailio PATHS ENV VCPKG_ROOT)
    find_file(MAILIO_LIB lib/mailio.lib PATHS ENV VCPKG_ROOT)
else ()
    find_path(MAILIO_INCLUDE_DIR mailio PATHS ENV VCPKG_ROOT)
    find_file(MAILIO_LIB lib/libmailio.a PATHS ENV VCPKG_ROOT)
endif ()
